
name: Automated Tests

on:
  push:
    branches:
      - '*'         # matches every branch
      - '*/*'       # matches every branch containing a single '/'
      #- '!master'   # excludes master
      #- '!develop'   # excludes develop

env:
  ENVIRONMENT: dev
  KUBECTL_VERSION: '1.18.2'
  KUSTOMIZE_VERSION: '3.5.3'
  SKAFFOLD_VERSION: '1.10.0'

jobs:
  automated-tests:
    runs-on: ubuntu-latest

    steps:
      - name: Cache All
        id: cache-all
        uses: actions/cache@v2
        with:
          path: |
            cache-kubectl/kubectl
            cache-kubectl/skaffold
          key: all-k8s-tool-${{env.KUBECTL_VERSION}}

      - name: Manually install kubectl
        if: steps.cache-all.outputs.cache-hit != 'true'
        run: |
          mkdir cache-kubectl
          curl -L https://storage.googleapis.com/kubernetes-release/release/v${{env.KUBECTL_VERSION}}/bin/linux/amd64/kubectl -o cache-kubectl/kubectl
          sudo cp cache-kubectl/kubectl /usr/local/bin/kubectl
          sudo chmod 777 /usr/local/bin/kubectl
      
      - name: Kubectl Version
        run: |
          kubectl version --client=true
      
      # - name: Cache Kustomize
      #   id: cache-kustomize
      #   uses: actions/cache@v2
      #   with:
      #     path: cache-kustomize/kustomize
      #     key: x-kustomize-${{ env.KUSTOMIZE_VERSION }}
      
      - name: Manually install Kustomize
        # if: steps.cache-kustomize.outputs.cache-hit != 'true'
        run:
          mkdir cache-kustomize;
          curl -L https://github.com/kubernetes-sigs/kustomize/releases/download/kustomize%2Fv${{ env.KUSTOMIZE_VERSION }}/kustomize_v${{ env.KUSTOMIZE_VERSION }}_linux_amd64.tar.gz | tar xz;
          ls;
          mv kustomize cache-kustomize/kustomize;
          sudo cp cache-kustomize/kustomize /usr/local/bin/kustomize;
          sudo chmod 777 /usr/local/bin/kustomize;
      
      - name: Kustomize Version
        run: |
          kustomize version

      # - name: Cache Skaffold
      #   id: cache-skaffold
      #   uses: actions/cache@v2
      #   with:
      #     path: cache-skaffold/skaffold
      #     key: x-skaffold-${{env.SKAFFOLD_VERSION}}

      - name: Manually install skaffold
        if: steps.cache-all.outputs.cache-hit != 'true'
        run: |
          mkdir cache-skaffold
          curl -sL https://github.com/GoogleContainerTools/skaffold/releases/download/v${{env.SKAFFOLD_VERSION}}/skaffold-linux-amd64 -o cache-skaffold/skaffold
          sudo cp cache-skaffold/skaffold /usr/local/bin/skaffold
          sudo chmod 777 /usr/local/bin/skaffold
      
      - name: Skaffold version
        run: |
          echo 'boom'
          ls -als /usr/local/bin
          skaffold version