
name: Automated Tests

on:
  push:
    branches:
      - '*'         # matches every branch
      - '*/*'       # matches every branch containing a single '/'
      #- '!master'   # excludes master
      #- '!develop'   # excludes develop

env:
  ENVIRONMENT: dev
  KUBECTL_VERSION: '1.18.1'


jobs:
  automated-tests:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Hack to see if cache can introspect bin folder
        run: |
          sudo chmod -R 777 /usr/local/bin

      - name: Cache Kubectl
        id: cache-kubectl
        uses: actions/cache@v2
        with:
          path: /usr/local/bin/kubectl
          key: kubectl-${{ env.KUBECTL_VERSION }}

      - name: Manually install kubectl
        if: steps.cache-kubectl.outputs.cache-hit != 'true'
        run: |
          sudo curl -L https://storage.googleapis.com/kubernetes-release/release/v${{env.KUBECTL_VERSION}}/bin/linux/amd64/kubectl -o /usr/local/bin/kubectl
          sudo chmod 777 /usr/local/bin/kubectl
      
      - name: Manually install kubectl
        run: |
          echo ${{ steps.cache-kubectl.outputs.cache-hit }}
      
      - name: Manually install kubectl
        run: |
          kubectl -h