
name: Automated Tests

on:
  push:
    branches:
      - '*'         # matches every branch
      - '*/*'       # matches every branch containing a single '/'
      #- '!master'   # excludes master
      #- '!develop'   # excludes develop

env:
  ENVIRONMENT: dev
  GITHUB_SHA: ${{ github.sha }}


jobs:
  automated-tests:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: echo bash version
        run: |
          echo "Bash Version is:"
          bash --version

      - name: Promote data
        run: |
          declare -a arr=([dev]="edge" [test]="dev" [2]="b" [3]="2" [4]="c" [5]="3")
          src_env=${arr[${ENVIRONMENT}]}
          dest_env=${ENVIRONMENT}
          echo "Src Env = $src_env"
          echo "Dest Env = $dest_env"
          echo "gs://base-bucket-${src_env}/folder-name/* gs://base-bucket-${dest_env}/folder-name"
