
name: Automated Tests

on:
  push:
    branches:
      - '*'         # matches every branch
      - '*/*'       # matches every branch containing a single '/'
      #- '!master'   # excludes master
      #- '!develop'   # excludes develop

env:
  ENVIRONMENT: dev
  KUBECTL_VERSION: '1.18.2'


jobs:
  automated-tests:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Check version
        run: |
          curl --version

      - name: confirm url
        run: |
          echo https://storage.googleapis.com/kubernetes-release/release/v${{env.KUBECTL_VERSION}}/bin/linux/amd64/kubectl

      # - name: Cache Kubectl
      #   id: cache-kubectl
      #   uses: actions/cache@v2
      #   with:
      #     path: /usr/local/bin/kubectl
      #     key: kubectl-${{ env.KUBECTL_VERSION }}

      - name: Manually install kubectl
        # if: steps.cache-kubectl.outputs.cache-hit != 'true'
        run: |
          curl -sL https://storage.googleapis.com/kubernetes-release/release/v${{env.KUBECTL_VERSION}}/bin/linux/amd64/kubectl -o /usr/local/bin/kubectl
          chmod +x /usr/local/bin/kubectl
