
name: Automated Tests

on:
  push:
    branches:
      - '*'         # matches every branch
      - '*/*'       # matches every branch containing a single '/'
      #- '!master'   # excludes master
      #- '!develop'   # excludes develop

env:
  ENVIRONMENT: dev
  KUBECTL_VERSION: '1.18.1'


jobs:
  automated-tests:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Cache Kubectl
        id: cache-kubectl
        uses: actions/cache@v2
        with:
          path: cache-kubectl/kubectl
          key: kubectl-${{ env.KUBECTL_VERSION }}

      - name: Manually install kubectl
        if: steps.cache-kubectl.outputs.cache-hit != 'true'
        run: |
          mkdir cache-kubectl
          sudo curl -L https://storage.googleapis.com/kubernetes-release/release/v${{env.KUBECTL_VERSION}}/bin/linux/amd64/kubectl -o cache-kubectl/kubectl
          sudo cp cache-kubectl/kubectl /usr/local/bin/kubectl
          sudo chmod 777 /usr/local/bin/kubectl
      
      - name: Kubectl Version
        run: |
          kubectl version --client=true